# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-website
  cancel-in-progress: true

jobs:
  build:
    concurrency: publish-to-website
    if: github.repository == 'keycloak/keycloak-web'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: ./mvnw -B -s mvn-rel-settings.xml package -Dpublish
    - name: Publish website contents as a release
      # This way it can be consumed in a simple way in the keycloak.github.io repository
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # language=bash
      run: |
        if ( gh release view website-contents &> /dev/null ); then
          echo 'release exists'
        else
          gh release create website-contents --title "Website contents" --draft
        fi
        tar -cvzf contents.tar.gz -C target/web .
        gh release upload website-contents contents.tar.gz --clobber
        gh release edit website-contents --draft=false
    - name: Install SSH Client ðŸ”‘
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        SSH: true
        REPOSITORY_NAME: keycloak/keycloak.github.io
        BRANCH: main
        FOLDER: target/web
        CLEAN: true
        CLEAN_EXCLUDE: '["docs", "docs-api"]'
